"""Streamlit dashboard for the Procurement Pre-Payment Exception Review agent.

Runs entirely on synthetic data. In mock mode (default) every number and
recommendation on screen comes straight from the deterministic rule engine
in src/engine.py -- no API key, no network calls required.
"""
from __future__ import annotations

import os

import pandas as pd
import streamlit as st

from src import engine, llm
from src.models import Exception as ExceptionRecord

st.set_page_config(page_title="Procurement Exception Review", layout="wide")

MOCK_MODE = os.getenv("MOCK_MODE", "true").strip().lower() != "false"


@st.cache_data
def _load_and_detect():
    purchase_orders, suppliers, budgets, invoices = engine.load_data()
    exceptions = engine.detect_all(purchase_orders, suppliers, budgets, invoices)
    return exceptions


def _exceptions_to_frame(exceptions: list[ExceptionRecord]) -> pd.DataFrame:
    rows = []
    for exc in exceptions:
        status = st.session_state["review_status"].get(exc.unique_id, "Open")
        rows.append(
            {
                "PO ID": exc.po_id,
                "Exception Type": exc.exception_type,
                "Department": exc.department,
                "Supplier": exc.supplier_name or exc.supplier_id,
                "Financial Exposure ($)": exc.financial_exposure,
                "Severity": exc.severity,
                "Review Status": status,
                "_unique_id": exc.unique_id,
            }
        )
    return pd.DataFrame(rows)


def main() -> None:
    st.title("Procurement Pre-Payment Exception Review")
    st.caption(
        "Reviews synthetic purchase orders, suppliers, budgets, and invoices to surface "
        "pre-payment exceptions, prioritized by financial impact, with a recommended action for each."
    )

    if MOCK_MODE:
        st.info("Running in MOCK_MODE (default). All detection and numbers below are real, "
                "deterministic rule output over synthetic data -- no API key required.", icon="🔒")
    else:
        st.success("Running in LIVE mode. Detection and exposure numbers are still 100% rule-based; "
                   "only the written explanation below is generated by Claude.", icon="🤖")

    if "review_status" not in st.session_state:
        st.session_state["review_status"] = {}

    exceptions = _load_and_detect()

    if not exceptions:
        st.success("No pre-payment exceptions detected in the current dataset.")
        return

    by_id = {exc.unique_id: exc for exc in exceptions}

    # ------------------------------------------------------------------
    # Summary metrics row
    # ------------------------------------------------------------------
    total_exposure = sum(e.financial_exposure for e in exceptions)
    col1, col2, col3 = st.columns([1, 1, 2])
    col1.metric("Total Exceptions", len(exceptions))
    col2.metric("Total Financial Exposure", f"${total_exposure:,.0f}")

    counts_by_type = pd.Series([e.exception_type for e in exceptions]).value_counts()
    with col3:
        st.write("**Count by exception type**")
        st.dataframe(
            counts_by_type.rename_axis("exception_type").reset_index(name="count"),
            hide_index=True,
            use_container_width=True,
        )

    st.divider()

    # ------------------------------------------------------------------
    # Filterable, prioritized table
    # ------------------------------------------------------------------
    st.subheader("Prioritized Exceptions (by financial exposure)")

    all_types = sorted({e.exception_type for e in exceptions})
    all_departments = sorted({e.department for e in exceptions if e.department})

    filter_col1, filter_col2 = st.columns(2)
    selected_types = filter_col1.multiselect("Filter by exception type", all_types, default=all_types)
    selected_departments = filter_col2.multiselect("Filter by department", all_departments, default=all_departments)

    filtered = [
        e for e in exceptions
        if e.exception_type in selected_types and (e.department in selected_departments or not e.department)
    ]

    frame = _exceptions_to_frame(filtered)
    st.dataframe(
        frame.drop(columns=["_unique_id"]),
        use_container_width=True,
        hide_index=True,
    )

    st.divider()

    # ------------------------------------------------------------------
    # Detail view + acknowledge/escalate (human-in-the-loop action)
    # ------------------------------------------------------------------
    st.subheader("Review an exception")

    if frame.empty:
        st.warning("No exceptions match the current filters.")
        return

    options = frame["_unique_id"].tolist()

    def _label(uid: str) -> str:
        e = by_id[uid]
        return f"{e.po_id} — {e.exception_type} — ${e.financial_exposure:,.2f} ({e.severity})"

    selected_uid = st.selectbox("Select an exception to review", options, format_func=_label)
    selected_exception = by_id[selected_uid]

    detail_col, action_col = st.columns([3, 1])

    with detail_col:
        st.markdown(f"**PO:** {selected_exception.po_id}  |  **Department:** {selected_exception.department}  |  "
                    f"**Supplier:** {selected_exception.supplier_name or selected_exception.supplier_id}")
        st.markdown(f"**Financial exposure:** ${selected_exception.financial_exposure:,.2f}  "
                    f"|  **Severity:** {selected_exception.severity}")
        st.write(llm.generate_explanation(selected_exception))

    with action_col:
        current_status = st.session_state["review_status"].get(selected_uid, "Open")
        st.write(f"Current status: **{current_status}**")

        # This is the human-in-the-loop control point: an AP reviewer must
        # explicitly acknowledge or escalate every exception before payment
        # proceeds. This demo records that decision in session state only --
        # no payment system or workflow tool is actually called.
        if st.button("Acknowledge", use_container_width=True):
            st.session_state["review_status"][selected_uid] = "Acknowledged"
            st.rerun()
        if st.button("Escalate", use_container_width=True):
            st.session_state["review_status"][selected_uid] = "Escalated"
            st.rerun()

    st.caption(
        "Acknowledge/Escalate marks this exception's review status for this session only, "
        "standing in for a human approval workflow. It does not release or block payment in any real system."
    )


if __name__ == "__main__":
    main()
